# 데이터 인코딩
    원-핫 인코딩(One hot encoding): 고유 값에 해당하는 칼럼만 1, 나머지는 0

In [3]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import numpy as numpy

items = ['버스', '지하철', '택시', '비행기', '자전거', '자전거', '배', '배']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1, 1) # flatten

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(encoder.classes_)
print(oh_labels.toarray()) 
print(oh_labels.shape)

['배' '버스' '비행기' '자전거' '지하철' '택시']
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
(8, 6)


## pandas를 이용하여 더욱 간단하게 처리하는 법

In [5]:
import pandas as pd 

df = pd.DataFrame({'item': ['버스', '지하철', '택시', '비행기', '자전거', '자전거', '배', '배']})
pd.get_dummies(df)

item_배  item_버스  item_비행기  item_자전거  item_지하철  item_택시
0       0        1         0         0         0        0
1       0        0         0         0         1        0
2       0        0         0         0         0        1
3       0        0         1         0         0        0
4       0        0         0         1         0        0
5       0        0         0         1         0        0
6       1        0         0         0         0        0
7       1        0         0         0         0        0